### PR TITLE
Bump the version

### PR DESCRIPTION
**Pull request by atomaka**
Version bump; not much else to say.

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Did you test it?

**Comment by atomaka** [comment]
I did.  The current version of this container did not function.  I received a javascript error with it. So I bumped the version to the latest, rebuilt the container, pushed it to a private registry and it is working.

**Comment by jakzal** [comment]
👍 for this. The currently used version is simply broken.

**Comment by ubergesundheit** [comment]
thank you!

**Pull request merged**
